# System [/api/system]

## System Status [GET]

Acquires a session to be used in subsequent calls to identify the authenticated user.

+ Request (application/json)

    + Attributes(LoginCredentials)
        
+ Response 201 (application/json)

    + Attributes(Credentials)

## Delete session [DELETE]

This call effectively logs out the authenticated session from the backend.

+ Request (text/plain)
    + Headers

            Authorization: Token=<Authentication-Token>

+ Response 204



# User Management [/api/user]

## Change Password [POST]

Sets a new password for the authenticated user.

+ Request (application/json)
    + Headers

            Authorization: Token=<authentication_token>

    + Attributes(NewCredentials)

+ Response 201

