FORMAT: 1A


# SupaBRCK Local Management API

This API exposes state and configuration interfaces for SupaBRCK.

The API operates with the assumption that the device comes configured with one admin user.
The password should ideally be set during provisioning.

All failures will respond with a response containing the error_code and the reason for the failure.

    {
        "error_code": 2020,
        "error_reason": "The concrete reason if available for the failure"
    }

{{ partial "authentication.apib" }}

{{ partial "data_structures.apib"}}

{{ partial "system.apib" }}