# Data Structures

## Error

+ error_code: 5050 (number, required)
+ error_reason: The reason (string, required)


## LoginCredentials

+ username: admin (string, required)
+ password: admin (string, required)

## Credentials

+ token: 3ece2bb9fb7d3667d0056741db4ca23cd875e4c0011a20c737f42738fe4ff162 (string, required)
+ expiry: 1516101701 (number, required)


## NewCredentials

+ previous_password: password (string, required)
+ new_password: newpassword (string, required)