type: object
properties:
  soc_on:
    $ref: '#/definitions/StateOfCharge'
  soc_off:
    $ref: '#/definitions/StateOfCharge'
  on_time:
    $ref: '#/definitions/Time'
  off_time:
    $ref: '#/definitions/Time'
